import type { RoomResponse } from "@/lib/schemas/room-schema"

// Build a portable markdown report from a finished THE ROOM analysis.
// Pasted into Slack, Notion, or a Google Doc, it should read cleanly.

function trendingLabel(t: string) {
  switch (t) {
    case "growing":
      return "↑ growing"
    case "stable":
      return "→ stable"
    case "fading":
      return "↓ fading"
    default:
      return "? unclear"
  }
}

export function buildReportMarkdown({
  result,
  idea,
  audience,
}: {
  result: RoomResponse
  idea: string
  audience: string
}) {
  const lines: string[] = []

  lines.push("# THE ROOM — reality check")
  lines.push("")
  lines.push(`**Idea:** ${idea}`)
  lines.push(`**Audience:** ${audience}`)
  lines.push("")

  // Verdict
  lines.push("## Verdict")
  lines.push(
    `**Reality score:** ${result.verdict.reality_score}/10 · ${trendingLabel(
      result.verdict.trending
    )}`
  )
  lines.push(`**${result.verdict.headline}**`)
  lines.push("")
  lines.push(result.verdict.summary)
  lines.push("")

  // Voices
  lines.push("## Voices from the internet")
  lines.push("")
  result.voices.forEach((v) => {
    const verified = v.source_verified && v.source_url ? " ✓ verified" : ""
    const link = v.source_url ? ` — ${v.source_url}` : ""
    lines.push(
      `### #${v.voice_index} · @${v.username} · ${v.source_name}${verified}`
    )
    lines.push(`> ${v.quote}`)
    lines.push(`Sentiment: **${v.sentiment}** · ${v.date_relative}${link}`)
    lines.push("")
  })

  // Sentiment breakdown
  const sb = result.sentiment_breakdown
  const sentLine = (
    ["pain", "desire", "skepticism", "praise", "frustration"] as const
  )
    .map((k) => `${k}: ${sb[k]}`)
    .join(" · ")
  lines.push("## Signal breakdown")
  lines.push(`Sentiment counts — ${sentLine}`)
  if (result.source_breakdown.length > 0) {
    lines.push("")
    lines.push("Sources:")
    const sortedSources = [...result.source_breakdown].sort(
      (a, b) => b.count - a.count
    )
    for (const s of sortedSources) {
      lines.push(`- ${s.source_type}: ${s.count}`)
    }
  }
  lines.push("")

  // Personas
  lines.push("## The room reacts")
  result.personas.forEach((p) => {
    lines.push("")
    lines.push(`### ${p.name}, ${p.age} — ${p.occupation} _(${p.color})_`)
    lines.push(p.context)
    lines.push("")
    lines.push(`> _Gut reaction:_ ${p.gut_reaction}`)
    lines.push(
      `**Buy:** ${p.scores.buy} · **Trust:** ${p.scores.trust} · **Share:** ${p.scores.share}`
    )
  })
  lines.push("")

  // Sharper angles
  lines.push("## Sharper angles")
  result.sharper_angles.forEach((a, idx) => {
    lines.push("")
    lines.push(`**${idx + 1}.** ${a.angle}`)
    lines.push(`  - Borrows: _"${a.audience_language_borrowed}"_`)
    lines.push(`  - Inspired by voice #${a.inspired_by_voice_index}`)
  })
  lines.push("")
  lines.push("---")
  lines.push("_Generated by THE ROOM · grounded in Google Search_")

  return lines.join("\n")
}
